version: "3.8"

services:
  db:
    container_name: fastapi-db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi-db
    volumes:
      - fastapi-db:/var/lib/postgresql/data

volumes:
  fastapi-db:
    name: fastapi-db
    driver: local