"""init

Revision ID: 6535e08483ba
Revises: 
Create Date: 2023-06-18 17:01:54.812073

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision = '6535e08483ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_models',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('technical_name', sa.String(), nullable=True),
    sa.Column('no_readeable_attribute', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_models_id'), 'device_models', ['id'], unique=False)
    op.create_index(op.f('ix_device_models_technical_name'), 'device_models', ['technical_name'], unique=True)
    op.create_table('devices',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('device_model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_model_id'], ['device_models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number', 'device_model_id')
    )
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_index(op.f('ix_devices_serial_number'), 'devices', ['serial_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_serial_number'), table_name='devices')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_device_models_technical_name'), table_name='device_models')
    op.drop_index(op.f('ix_device_models_id'), table_name='device_models')
    op.drop_table('device_models')
    # ### end Alembic commands ###
